version: '3.8'

services:
  email-processor:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: email-processor-api
    ports:
      - "8000:8000"
    volumes:
      # Mount email_format.txt để dễ update format
      - ./email_format.txt:/app/email_format.txt:ro
      # Optional: Mount logs nếu cần
      # - ./logs:/app/logs
    env_file:
      # Load environment variables từ .env
      - .env
    environment:
      - TZ=Asia/Ho_Chi_Minh
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - email-network

networks:
  email-network:
    driver: bridge

