services:
  email-processor:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: email-processor-api
    ports:
      - "8000:8000"
    volumes:
      # Mount email_format.txt để dễ update format
      - ./email_format.txt:/app/email_format.txt:ro
      # Mount logs để dễ debug
      - ./logs:/app/logs
    env_file:
      # Load environment variables từ .env
      - .env
    environment:
      - TZ=Asia/Ho_Chi_Minh
    restart: always
    # Resource limits để tránh OOM
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          cpus: '0.25'
          memory: 256M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s
    networks:
      - email-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  email-network:
    driver: bridge

